name: Build and Release Docker Image

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: 'Blockcore.TipBot'

    steps:
      - uses: actions/checkout@v2

      - name: Log Variables
        run: |
          echo "action - ${{ github.event.action }}"
          echo "url - ${{ github.event.release.url }}"
          echo "assets_url - ${{ github.event.release.assets_url }}"
          echo "id - ${{ github.event.release.id }}"
          echo "tag_name - ${{ github.event.release.tag_name }}"
          echo "assets - ${{ github.event.assets }}"
          echo "assets[0] - ${{ github.event.assets[0] }}"
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/Dockerfile.Release"]'
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Download Release Assets
        run: |
          curl -s -L -o release.tar.gz https://github.com/block-core/blockcore-tipbot/releases/download/${{ github.event.release.tag_name }}/${{ env.PROJECT_NAME }}-${{ github.event.release.tag_name }}-linux-x64.tar.gz
          mkdir release
          tar -xvf release.tar.gz -C release

      - name: Build the Docker container image
        run: docker build -f "./src/TipBot/Dockerfile.Release" -t blockcore/tipbot:latest -t blockcore/tipbot:${{ github.event.release.tag_name }} "."

#      - name: Login and Push to Docker Registry
#        run: |
#          docker login -u "sondreb" -p "${{secrets.DockerHubSecret}}"
#          docker push blockcore/tipbot